[tools]
python = "3.12"
uv = "latest"

[env]
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist
_.path = ["{{ vars.mise_bin_dir }}"]

[vars]
mise_bin_dir = "{{ config_root }}/.mise_bin"

[hooks]
enter = "mise run build"

[tasks.build]
hide = true
silent = true
run = """
    # mise install
     mise install &> /dev/null

    # Install the packages
     rm -rf {{ vars.mise_bin_dir }}
     mkdir -p {{ vars.mise_bin_dir }}
     echo 'uv pip $@' > {{ vars.mise_bin_dir }}/pip
     echo 'uv pip $@' > {{ vars.mise_bin_dir }}/pip3
     chmod +x {{ vars.mise_bin_dir }}/pip
     chmod +x {{ vars.mise_bin_dir }}/pip3
"""
