openapi: 3.0.0
info:
  title: SQL Copilot API
  version: 1.0.0
  description: API for processing natural language queries and generating SQL.

paths:
  /query:
    post:
      summary: Process a natural language query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The natural language query prompt.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  sql:
                    type: string
                    description: The generated SQL query.
                  results:
                    type: array
                    items:
                      type: object
                      description: The query results.
